// Generated by Vectra — do not edit.
// 3 node(s) · 2 prop(s) · 0 warning(s).
//
// The elements are Vectra's semantic primitives: map `Rect`, `Circle`, `Arc`,
// `Path` and `Group` onto your renderer (they match the SVG elements one to one).

interface SceneProps {
  base: number; // 40
  gap: number; // 8
}

export function Scene({ base, gap }: SceneProps) {
  return (
    <Group>
      {/* card */}
      <Rect x={0} y={0} width={base * 2} height={60} cornerRadius={gap} fill="#2266ee" opacity={1}/>
      {/* dot */}
      <Circle cx={140} cy={30} r={30} fill="#2266ee" opacity={1}/>
      {/* half */}
      <Arc cx={210} cy={30} r={30} startAngle={0} endAngle={3.141593} fill="#2266ee" opacity={1}/>
    </Group>
  );
}
