//! The **React/TSX exporter** (Task 8.0, RULE 2 — "the moat").
//!
//! The rule: "the exporter must map `Parameter::Variable` and
//! `Parameter::Expression` to component props. A rectangle with `width = $base * 2`
//! must export as `<Rect width={base * 2} />`, NOT `<Rect width="200" />`. The
//! exporter must extract all unique variables used in the document and define
//! them as typed props in the component signature."
//!
//! Which is why the exporter is so short: the hard part already happened in the
//! IR. `ExportParam::code` is the parametric text, `ExportParam::vars` are the
//! variables it reads, and `ExportIR::props` is the union — this module only
//! spells them in TypeScript.
//!
//! ## What the output is
//!
//! A single functional component. The elements are Vectra's **semantic
//! primitives** — `Rect`, `Circle`, `Arc`, `Path`, `Group` — which map 1:1 onto
//! the SVG elements of the same shape, so the generated file is valid JSX against
//! either a custom renderer or a thin wrapper over `react-dom`. That is a
//! deliberate choice over emitting raw `<svg>` markup: the IR is semantic, and a
//! consumer that wants `<circle>` can have it, while a consumer that wants it
//! *parametric* cannot get it any other way.
//!
//! ```tsx
//! interface SceneProps {
//!   base: number;
//! }
//!
//! export function Scene({ base }: SceneProps) {
//!   return (
//!     <Group>
//!       <Rect x={0} y={0} width={base * 2} height={30} cornerRadius={0} fill="#2266ee" opacity={1} />
//!     </Group>
//!   );
//! }
//! ```

use crate::ir::{
    fmt_number, ExportColor, ExportGeometry, ExportIR, ExportNode, ExportParam, ExportStyle,
};

/// Knobs a caller may want; the defaults are what the UI uses.
#[derive(Debug, Clone)]
pub struct ReactOptions {
    /// The component's name (`export function <name>`).
    pub component_name: String,
    /// Emit `{/* node name */}` before each element.
    pub include_comments: bool,
}

impl Default for ReactOptions {
    fn default() -> Self {
        Self {
            component_name: "Scene".to_string(),
            include_comments: true,
        }
    }
}

/// Export the IR as a React component module.
pub fn export_react(ir: &ExportIR) -> String {
    export_react_with(ir, &ReactOptions::default())
}

/// Export the IR as a React component module, with options.
pub fn export_react_with(ir: &ExportIR, options: &ReactOptions) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Vectra — do not edit.\n");
    out.push_str(&format!(
        "// {} node(s) · {} prop(s) · {} warning(s).\n",
        ir.nodes.len(),
        ir.props.len(),
        ir.warnings.len()
    ));
    out.push_str("//\n");
    out.push_str(
        "// The elements are Vectra's semantic primitives: map `Rect`, `Circle`, `Arc`,\n",
    );
    out.push_str(
        "// `Path` and `Group` onto your renderer (they match the SVG elements one to one).\n",
    );
    for warning in &ir.warnings {
        out.push_str(&format!("// ! {}\n", single_line(warning)));
    }
    out.push('\n');

    if !ir.props.is_empty() {
        out.push_str("interface ");
        out.push_str(&format!("{}Props", options.component_name));
        out.push_str(" {\n");
        for prop in &ir.props {
            out.push_str(&format!(
                "  {}: {}; // {}\n",
                crate::ir::sanitize_ident(&prop.name),
                type_name(prop.ty),
                fmt_number(prop.value)
            ));
        }
        out.push_str("}\n\n");
    }

    if uses_clamp(ir) {
        out.push_str(
            "// `clamp` is total in Vectra (NaN propagates, degenerate bounds collapse) —\n\
             // JavaScript's `Math.min/Math.max` pair is not, so this is the same function.\n\
             const clamp = (value: number, lo: number, hi: number): number =>\n\
             \u{20} value < lo ? lo : value > hi ? hi : value;\n\n",
        );
    }

    let props = if ir.props.is_empty() {
        String::new()
    } else {
        let names: Vec<String> = ir
            .props
            .iter()
            .map(|prop| crate::ir::sanitize_ident(&prop.name))
            .collect();
        format!(
            "{{ {} }}: {}Props",
            names.join(", "),
            options.component_name
        )
    };
    out.push_str(&format!(
        "export function {name}({props}) {{\n  return (\n    <Group>\n",
        name = options.component_name,
    ));
    for node in &ir.nodes {
        if options.include_comments {
            out.push_str(&format!("      {{/* {} */}}\n", single_line(&node.name)));
        }
        out.push_str(&format!("      {}\n", element(node)));
    }
    out.push_str("    </Group>\n  );\n}\n");
    out
}

fn type_name(ty: crate::ir::ExportPropType) -> &'static str {
    match ty {
        crate::ir::ExportPropType::Number => "number",
    }
}

fn single_line(text: &str) -> String {
    text.replace('\n', " ").replace("*/", "*\\/")
}

/// One JSX element for one node.
fn element(node: &ExportNode) -> String {
    let geometry = match &node.geometry {
        ExportGeometry::Rect {
            x,
            y,
            width,
            height,
            corner_radius,
        } => format!(
            "<Rect x={{{}}} y={{{}}} width={{{}}} height={{{}}} cornerRadius={{{}}}{}/>",
            value(x),
            value(y),
            value(width),
            value(height),
            value(corner_radius),
            style(&node.style),
        ),
        ExportGeometry::Circle { cx, cy, radius } => format!(
            "<Circle cx={{{}}} cy={{{}}} r={{{}}}{}/>",
            value(cx),
            value(cy),
            value(radius),
            style(&node.style),
        ),
        ExportGeometry::Arc {
            cx,
            cy,
            radius,
            start_angle,
            end_angle,
        } => format!(
            "<Arc cx={{{}}} cy={{{}}} r={{{}}} startAngle={{{}}} endAngle={{{}}}{}/>",
            value(cx),
            value(cy),
            value(radius),
            value(start_angle),
            value(end_angle),
            style(&node.style),
        ),
        ExportGeometry::Path { d } => match d {
            Some(d) => format!("<Path d=\"{}\"{}/>", escape_jsx(d), style(&node.style)),
            None => format!(
                "{{/* `{}` has no resolved geometry (animated or procedural) */}}<Path/>",
                single_line(&node.name)
            ),
        },
        ExportGeometry::Group { children } => {
            format!("<Group data-children={{{}}}/>", children.len())
        }
    };
    geometry
}

/// The slot, as JSX: parametric code in braces, or the drawn number.
fn value(param: &ExportParam) -> String {
    if param.is_parametric() {
        param.code.clone()
    } else {
        fmt_number(param.number())
    }
}

fn style(style: &ExportStyle) -> String {
    let mut out = String::new();
    out.push_str(&format!(" fill={}", color(&style.fill)));
    if let Some(stroke) = stroke(&style.stroke, &style.stroke_width) {
        out.push_str(&format!(
            " stroke={} strokeWidth={{{}}}",
            stroke,
            value(&style.stroke_width)
        ));
    }
    let opacity = style.opacity.number();
    if (opacity - 1.0).abs() > 1e-9 || style.opacity.is_parametric() {
        out.push_str(&format!(" opacity={{{}}}", value(&style.opacity)));
    }
    out
}

fn color(color: &ExportColor) -> String {
    if color.is_parametric() {
        format!("{{{}}}", color.code)
    } else {
        match color.value {
            Some(value) if value.a == 0 => "\"none\"".to_string(),
            Some(value) => format!("\"{}\"", value.to_hex()),
            None => "\"none\"".to_string(),
        }
    }
}

fn stroke(color: &ExportColor, width: &ExportParam) -> Option<String> {
    let visible = color.value.map(|value| value.a > 0).unwrap_or(false) && width.number() > 0.0;
    visible.then(|| color_attr(color))
}

fn color_attr(color: &ExportColor) -> String {
    if color.is_parametric() {
        format!("{{{}}}", color.code)
    } else {
        match color.value {
            Some(value) => format!("\"{}\"", value.to_hex()),
            None => "\"none\"".to_string(),
        }
    }
}

/// Does any emitted code call Vectra's `clamp`? If so the module declares it.
fn uses_clamp(ir: &ExportIR) -> bool {
    let mut codes: Vec<&str> = Vec::new();
    for node in &ir.nodes {
        for param in node.geometry.parameters() {
            codes.push(&param.code);
        }
        codes.push(&node.style.fill.code);
        codes.push(&node.style.stroke.code);
        codes.push(&node.style.stroke_width.code);
        codes.push(&node.style.opacity.code);
    }
    codes.iter().any(|code| code.contains("clamp("))
}

fn escape_jsx(text: &str) -> String {
    text.replace('"', "&quot;")
}
